### ISSUE TITLE
Board is wrong

### ISSUE THREAD

**Issue by HarryDietrich** [Laci1953/Software-for-Z80ALL-retro-computer#1]
Hi,
the board is wrong. H1 is a white field.
Regards, Harry

**Comment by Laci1953** [comment]
Thanks, fixed!

**Comment by Laci1953** [comment]
Thanks, I just fixed the bug and published the correct files...regards,Ladislau

    On Monday, July 3, 2023 at 08:39:37 PM GMT+3, HarryDietrich ***@***.***> wrote:  
 
 


Hi,
the board is wrong. H1 is a white field.
Regards, Harry
